baseURL = "https://aelias.dev"
relativeURLs = true
title = "Aelias"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[pagination]
  pagerSize =  5

[module]
  [[module.mounts]]
    source = "/Users/eliaslittle/Blog/Blog/posts"
    target = "content/posts"
  
  [[module.mounts]]
    source = "/Users/eliaslittle/Blog/Blog/reading-log"
    target = "content/reading-log"
  
  [[module.mounts]]
    source = "/Users/eliaslittle/Blog/Blog/about.md"
    target = "content/about.md"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      wikilink = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[minify]
disableXML = false
minifyOutput = false

[params]
  env = "production"
  title = "ExampleSite"
  description = "ExampleSite description"
  keywords = [ "Blog", "Portfolio", "PaperMod" ]
  author = "Me"
  images = [ "<link or path of image for opengraph, twitter-cards>" ]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  math = true

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Aelias"
  # icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Howdy friend ðŸ‘‹"
  Content = """Welcome!

  I'm Elias, however you might have found this, it's mostly a collection of my thoughts and short form writing. 
  Most of it is focused on Math, Machine Learning, and Computer Science. Feel free to reach out, I'd love to chat."""

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/eliasjlittle"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/EliasLittle"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 5

[[menu.main]]
identifier = "reading log"
name = "Reading Log"
url = "/reading-log/"
weight = 10

#[[menu.main]]
#identifier = "categories"
#name = "Categories"
#url = "/categories/"
#weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

#[[menu.main]]
#identifier = "conjectures"
#name = "Conjectures"
#url = "/conjectures/"
#weight = 30

# [[menu.main]]
# identifier = "EliasL.com"
# name = "EliasL.com"
# url = "https://eliasl.com"
# weight = 30

